version: '3'

services:

  myapp-mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=todoDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssw0rd
    ports:
      - 3306:3306

  myapp-main:
    image: todo-app
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=P@ssw0rd
      - DATABASE_NAME=todoDb
      - DATABASE_PORT=3306