server:
  port: 8080
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:todoDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    url: jdbc:h2:mem:todoDb
    user: sa
    password: